services:
  nextjs-blue:
    container_name: main-nextjs-blue
    image: ${NEXTJS_BLUE_IMAGE}:${TAG_BLUE}
    networks:
      - main-protostar
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nextjs-green:
    container_name: main-nextjs-green
    image: ${NEXTJS_GREEN_IMAGE}:${TAG_GREEN}
    networks:
      - main-protostar
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  main-protostar:
    external: true
    name: main-protostar